Determine the Rank of Matrix

In [1]:
import numpy as np

# Define the matrix A
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Compute the rank
rank = np.linalg.matrix_rank(A)
print(f"Rank of matrix A: {rank}")

Rank of matrix A: 2


In [2]:
import numpy as np

# Define the coefficient matrix A
A = np.array([[2, 1, -1],
              [-3, -1, 2],
              [-2, 1, 2]])

# Define the constant vector b
b = np.array([8, -11, -3])

# Check if the matrix A is invertible
if np.linalg.det(A) != 0:  # If the determinant is not zero
    # Calculate the solution using the inverse of A
    x = np.linalg.inv(A).dot(b)
    print(f"Solution: {x}")
else:
    print("Matrix A is not invertible. No unique solution.")


Solution: [ 2.  3. -1.]


Student Practice Problems

In [3]:
# Define the matrix
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Compute the rank
rank = np.linalg.matrix_rank(A)

print("Matrix A:")
print(A)
print(f"\nRank of matrix A: {rank}")

# Explanation
print("\nExplanation:")
print("The rank of this matrix is 2 because:")
print("1. It has 3 rows, but the third row is a linear combination of the first two.")
print("2. Specifically, row3 = 2 * row2 - row1")
print("3. This means there are only 2 linearly independent rows or columns.")

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Rank of matrix A: 2

Explanation:
The rank of this matrix is 2 because:
1. It has 3 rows, but the third row is a linear combination of the first two.
2. Specifically, row3 = 2 * row2 - row1
3. This means there are only 2 linearly independent rows or columns.


Solving 3x3 System of Equations

In [4]:
import numpy as np


A = np.array([[1, 1, 1],
              [2, 4, 3],
              [0, 0, 1]])

b = np.array([6, 18, 5])

# Check if the matrix A is invertible
if np.linalg.det(A) != 0:  # If the determinant is not zero
    # Calculate the solution using the inverse of A
    x = np.linalg.inv(A).dot(b)  # Use dot product to find the solution vector
    print(f"Solution: x = {x[0]}, y = {x[1]}, z = {x[2]}")
else:
    print("Matrix A is not invertible. No unique solution.")

Solution: x = 0.5, y = 0.5, z = 5.0


Solving a 4x4 System of Equations

In [5]:
import numpy as np


A = np.array([[1, 1, 1, 1],
              [2, 1, 0, 3],
              [4, 3, 2, 1],
              [3, 0, 5, 2]])

# Define the constant vector b
b = np.array([10, 11, 20, 15])

# Check if the matrix A is invertible
if np.linalg.det(A) != 0:  # If the determinant is not zero
    # Calculate the solution using the inverse of A
    x = np.linalg.inv(A).dot(b)  # Use dot product to find the solution vector
    print(f"Solution: x = {x[0]}, y = {x[1]}, z = {x[2]}, w = {x[3]}")
else:
    print("Matrix A is not invertible. No unique solution.")

Solution: x = -1.625, y = 6.0, z = 2.875, w = 2.75
